### ISSUE TITLE
Error: Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [dimafeng/typescript-react-mobx-template#1]
Похоже для скриптов нужен Питон... Ругается при установке App

**Comment by dimafeng** [comment]
@Dmitrij-Polyanin а на какой системе вы запускаете? Я проверял только на linux и mac - и там и там python идет из коробки, поэтому не исключаю, что что-то требует питон.

**Comment by DmitrijOkeanij** [comment]
На Windows, если нужно могу лог отправить более развёрнутый.
